### ISSUE TITLE
Failure with dev testthat

### ISSUE THREAD

**Issue by hadley** [TommyJones/mvrsquared#6] opened 2020-10-09 22:38 UTC
I think this is just a random failure because it hasn't cropped up in the previous two rounds of checks, but just a heads up in case it's a real problem. testthat is scheduled for CRAN submission on Monday.

```
── FAILURE (test-mvrsquared.R:44:3): Multithreading works as expected ──────────
round(r2, 3) not equal to round(s$r.squared, 3).
1/1 mismatches
[1] 0.848 - 0.849 == -0.001

── FAILURE (test-mvrsquared.R:50:3): Multithreading works as expected ──────────
`r2` not equal to 1 - ss[[1]]/ss[[2]].
1/1 mismatches
[1] 0.848 - 0.849 == -0.000959

══ testthat results  ═══════════════════════════════════════════════════════════
FAILURE (test-mvrsquared.R:44:3): Multithreading works as expected
FAILURE (test-mvrsquared.R:50:3): Multithreading works as expected

[ FAIL 2 | WARN 0 | SKIP 0 | PASS 23 ]
Error: Test failures
Execution halted
```

**Comment by TommyJones** [comment] 2020-10-10 03:14
Thanks for the heads up. I'll look into it.

**Comment by TommyJones** [comment] 2020-10-19 02:58
The same bug has cropped up on the CRAN Solaris build. Details below:

```
Check Details
Version: 0.1.0
Check: tests
Result: ERROR
     Running ‘spelling.R’
     Running ‘testthat.R’
    Running the tests in ‘tests/testthat.R’ failed.
    Complete output:
     > library(testthat)
     > library(mvrsquared)
     >
     > test_check("mvrsquared")
     ── 1. Failure: Multithreading works as expected (@test-mvrsquared.R#44) ───────
     round(r2, 3) not equal to round(s$r.squared, 3).
     1/1 mismatches
     [1] 0.82 - 0.849 == -0.029
    
     ── 2. Failure: Multithreading works as expected (@test-mvrsquared.R#50) ───────
     
r
2
 not equal to 1 - ss[[1]]/ss[[2]].
     1/1 mismatches
     [1] 0.82 - 0.849 == -0.029
    
     ══ testthat results ═══════════════════════════════════════════════════════════
     [ OK: 23 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 2 ]
     1. Failure: Multithreading works as expected (@test-mvrsquared.R#44)
     2. Failure: Multithreading works as expected (@test-mvrsquared.R#50)
    
     Error: testthat unit tests failed
     Execution halted
Flavor: r-patched-solaris-x86
```

**Comment by TommyJones** [comment] 2020-10-19 02:59
@hadley, do you have info on the OS you were using when you got this error?

**Comment by hadley** [comment] 2020-10-19 11:41
Linux

**Comment by TommyJones** [comment] 2020-10-21 01:29
Documenting my thought process here:

For some reason, sometimes, on linux distros multithreading causes a calculation that's non-deterministic. (So far, I have not been able to reproduce this on MacOS or Windows.)

Given the way that this is programmed (and the fact that the calculation is *usually* right) I don't think that this is caused by anything I'm doing in {mvrsquared}. In fact, it's just a parallel for loop. The sequential code is identical. This bug also didn't crop up on any previous checks during development or release, which involves CRAN on many operating systems, including several linux distros through R Hub.

All of this is a drawn out way of saying... I'm going to modify the test to not throw this error when running {testthat} tests. Instead of verifying the calculation, I'll have the test just verify the function call doesn't throw the error.

In parallel (and not under the gun of a CRAN takedown threat), I'll do some testing to see if this has something to do with {RCppThread}, something I can't yet fathom in {mvrsquared} code, sunspots, or something else.

**Comment by TommyJones** [comment] 2020-10-21 01:48
Another thought: This could be happening in {mvrsquared} which uses {RcppThread}'s `parallelFor` to loop over observations. Or this could be happening with the call to `summary.lm` which produces the r-squared for comparison in the test. 

To investigate this I can do 2 things:
* See if the `yhat = w * x` internal to {mvrsquared} gives the same `yhat` dumped out of `lm()` on different operating systems
* See if `summary.lm`'s `r.squared` has different values on different operating systems

This thought isn't going to change my approach to closing this issue described in https://github.com/TommyJones/mvrsquared/issues/6#issuecomment-713234096 Just documenting the thought so I can come back to it.

**Comment by TommyJones** [comment] 2020-10-21 02:06
ff9f2299a7a9e57c0937199142a376198f7a625e

**Closed as completed by TommyJones** 2020-10-21 02:06 UTC
